export const authConstant = {
  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const booksConstant = {
  ADDBOOKS_REQUEST: "ADDBOOKS_REQUEST",
  ADDBOOKS_SUCCESS: "ADDBOOKS_SUCCESS",
  ADDBOOKS_FAILURE: "ADDBOOKS_FAILURE",
  GETBOOKS_REQUEST: "GETBOOKS_REQUEST",
  GETBOOKS_SUCCESS: "GETBOOKS_SUCCESS",
  GETBOOKS_FAILURE: "GETBOOKS_FAILURE",
  UPDATE_BOOKS_REQUEST: "UPDATE_BOOKS_REQUEST",
  UPDATE_BOOKS_SUCCESS: "UPDATE_BOOKS_SUCCESS",
  UPDATE_BOOKS_FAILURE: "UPDATE_BOOKS_FAILURE",
  DELETE_BOOKS_REQUEST: "DELETE_BOOKS_REQUEST",
  DELETE_BOOKS_SUCCESS: "DELETE_BOOKS_SUCCESS",
  DELETE_BOOKS_FAILURE: "DELETE_BOOKS_FAILURE",
};
